version: "3.9"

services:

  payroll:
    build: payroll
    image: payroll
    container_name: payroll
    ports:
      - 8080:4567
    environment:
      - EMPLOYEES_URL_PROTOCOL=http
      - EMPLOYEES_URL_HOST=employees
      - EMPLOYEES_URL_PORT=4567

  employees:
    build: employees
    image: employees
    container_name: employees
    ports:
      - 7070:4567
